# A single CI script with github workflow
name: Tests

env:
  CUDA_PATH:

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [labeled]

jobs:
  build:
    env:
      var_a: ${{ env.CUDA_PATH != ''}}
      var_b: ${{ contains(github.event.pull_request.labels.*.name, 'run-workflow') || github.event_name == 'push' }}
    if: ${{ fromJSON(env.var_a) && fromJSON(env.var_b)}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, "3.10", "3.11"]
    uses: qiboteam/workflows/.github/workflows/rules-poetry.yml@main
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      poetry-extras: "--with analysis,tests"
    secrets: inherit
