# A single CI script with github workflow
name: Tests

env:
  CUDA_PATH:

on:
  push:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'run-workflow') || github.event_name == 'push' }} && env.CUDA_PATH != ''
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, "3.10"]
    uses: qiboteam/workflows/.github/workflows/rules-poetry.yml@main
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      pip-extras: "analysis,tests"
    secrets: inherit
